### ISSUE TITLE
Module generation fails: undefined method `issues_url'

### ISSUE THREAD

**Issue by Rovanion** [garethr/puppet-module-skeleton#89]
After cloning the repository, installing puppet and running install.sh I get the following error when trying to generate a new module:

```bash
$ puppet module generate a-whole-new-world
Notice: Generating module at /home/rovanion/source/a-whole-new-world
Error: undefined method `issues_url' for #<Puppet::ModuleTool::Metadata:0x00000000a6a928>
Error: Try 'puppet help module generate' for usage
```

This is running ```puppet version 3.4.3``` on ```Ubuntu 14.04.3```. I've been able to reproduce this on two machines.

Though it could just be that I'm horrible at reading instructions and did the same mistake on both.

I tried running test.sh on both machines but they in turn failed with the message:

```
+ bundle exec rake lint syntax rubocop spec
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
```

**Comment by garethr** [comment]
Mmm, I don't think it's explicitly stated anywhere but the skeleton is at least only tested on versions since 3.7.x. https://github.com/garethr/puppet-module-skeleton/blob/master/.travis.yml#L8

Maybe try and delete the following line from your local skeleton and rerun generate?
https://github.com/garethr/puppet-module-skeleton/blob/d2b6ca6d00b5d064421aff21f3db8a1f4032b1fb/skeleton/metadata.json.erb#L9

**Comment by Rovanion** [comment]
I can confirm that it works fine with puppet 3.8.3. I ended up with 3.8.3 after running dist-upgrades on both my machines so we'll just pretend that this bug doesn't exist any more since I can't really test it any more :D

**Comment by garethr** [comment]
@Rovanion Thanks :). If I see lots of requests (hopefully unlikely) I'll look to fix, but using a more recent Puppet version is definitely recommended. The latest version 4.2.x has lots of performance improvements and handy features.

**Comment by apollo-io** [comment]
Hi @garethr - that solution works for me on the stock puppet version for Solaris 11.2 - alas v3.4.1.

Thank you - this package is exactly what I've been looking for.
